services:
  - type: web
    name: fleure
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://innovalatinos:innovalatinos@cluster0.cinpcmb.mongodb.net/Fleure_DB?retryWrites=true&w=majority&appName=Cluster0
      - key: CLOUDINARY_URL
        value: cloudinary://645926898591627:u-Nr1A347QcTYNLY5Y1LWWxJ0jk@dhjnvfvtu
